/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_cpp_AlarmReceiver */

#ifndef _Included_org_cocos2dx_cpp_AlarmReceiver
#define _Included_org_cocos2dx_cpp_AlarmReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_cpp_AlarmReceiver
 * Method:    checkMission
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cocos2dx_cpp_AlarmReceiver_checkMission
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
